version: '3.8'

services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - pg_diploma_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always
    ports:
      - "5432:5432"

volumes:
  pg_diploma_data:

