version: '3.8'

services:
  db:
    image: postgres:15.1
    volumes:
      - pg_coursework_7_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: always

    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      timeout: 3s
      retries: 10
      interval: 3s


  api:
    image: artnicanov/todolist:latest
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - django_static:/opt/static
    command: python manage.py runserver 0.0.0.0:8000


  frontend:
    image: sermalenk/skypro-front:lesson-38
    ports:
      - "80:80"
    depends_on:
      api:
        condition: service_started
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - django_static:/usr/share/nginx/html/static

  bot:
    image: artnicanov/todolist:latest
    restart: always
    env_file: .env
    depends_on:
      frontend:
        condition: service_started
    command: python manage.py runbot

volumes:
  pg_coursework_7_data:
  django_static:
